= Foo Yong Qi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: UniLA

---

== Overview

UniLA is a desktop utilities application designed for NUS students who are typing oriented. UniLA provides an efficient and convenient solution for managing contact list and event list, contact interactions, planning meetings, setting up reminders, etc. The application is primarily concerned with CLI (Command Line Interface) Interaction, with a simple and intuitive GUI provided.

== Summary of contributions

* *Major enhancement*: added *the ability to automatically create a meeting event with persons*
** What it does: It allows users to create a meeting event among certain people, by automatically
*** searching for the earliest available timeslot among the requested people to meet
*** creating the meeting event in the event list
*** connecting the requested people to the event and
*** setting the details of the event (such as name, description etc.) as requested.
** Justification: This feature improves the product significantly because as the user's contact and event list grows, there may be too many people and events stored and it will be difficult for the user to find a suitable timing to meet the people he needs to. Thus the app must be able to conveniently help the user do so.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Minor enhancement*: added a switch command which allows the user to switch between person and events list view. All commands will also automatically switch accordingly or terminate depending on the current view of the window as the command was entered.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=yonggqiii[RepoSense Project Code Dashboard]]

* *Other contributions*:

** Improved UI
** Did cosmetic tweaks to existing contents of the README and updated UI
** PRs reviewed (with non-trivial review comments): [https://github.com/CS2103-AY1819S2-W16-1/main/pull/100[#100]]
** Helped team to fix bugs
** Maintained issue tracker

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=meet]

include::../UserGuide.adoc[tag=switch]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=meet]
